runtime: python27
api_version: 1
threadsafe: true

# Setup to be restricted to this Cloud Build.
env_variables:
  API_KEY: AIzaSyAYQ5kp6Vfu8rB2rvDLpZOOK_KzYWPqm5k

handlers:
  - url: /
    static_files: dist/joeldlc/index.html
    upload: dist/joeldlc/index.html
  - url: /
    static_dir: dist/
