steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:node-10.13.0'
    args: [ 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm:node-10.13.0'
    args: [ 'run', 'build', '--prod' ]
