steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]

  # Run unit tests
  - name: 'gcr.io/joeldlc-252516/ng'
    args: ['test', '--watch=false' ]
    env:
      - 'CHROME_BIN=/usr/bin/chromium-browser'

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build', '--prod' ]
