steps:
  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: [ 'install' ]

  # Build prod files
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: [ 'run', 'build', '--prod' ]
